/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crazy_mndk_HelloJni */

#ifndef _Included_com_crazy_mndk_HelloJni
#define _Included_com_crazy_mndk_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crazy_mndk_HelloJni
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crazy_mndk_HelloJni_stringFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
